flowchart LR
    id_Module_DataImporter(Data Importer):::NotStarted
    id_SubModule_AlpacaApi_Reader(Alpaca API Reader):::InProgress
    id_SubModule_GoogleTrendsApi(Google Trends API):::NotStarted

    id_Module_DataPreprocessor(Data Preprocessor):::NotStarted
    id_SubModule_TensorFlowFormatter(TensorFlow Formatter):::NotStarted

    id_Module_DecisionMaker(Decision Maker):::NotStarted
    id_SubModule_TensorFlowTrainer(TensorFlow Trainer):::NotStarted
    id_SubModule_TensorFlowExecutor(TensorFlow Executor):::NotStarted
    id_SubModule_TensorFlowBackup(TensorFlow Backup):::NotStarted

    id_Module_DataExporter(Data Exporter):::NotStarted
    id_SubModule_AlpacaApi_Writer(Alpaca API Writer):::NotStarted



    classDef NotStarted fill:#ff6666, stroke:#333
    classDef InProgress fill:#ffcc66, stroke:#333
    classDef Completed fill:#339966, stroke:#333



    subgraph id_Module_DataImporter [Data Importer]
        id_SubModule_AlpacaApi_Reader
        id_SubModule_GoogleTrendsApi
    end

    subgraph id_Module_DataPreprocessor [Data Preprocessor]
        id_SubModule_TensorFlowFormatter
    end

    subgraph id_Module_DecisionMaker [Decision Maker]
        id_SubModule_TensorFlowTrainer --> id_SubModule_TensorFlowExecutor
        id_SubModule_TensorFlowTrainer --> id_SubModule_TensorFlowBackup
    end

    subgraph id_Module_DataExporter [Data Exporter]
        id_SubModule_AlpacaApi_Writer
    end




    id_SubModule_AlpacaApi_Reader & id_SubModule_GoogleTrendsApi --> id_SubModule_TensorFlowFormatter
    id_SubModule_TensorFlowFormatter --> id_SubModule_TensorFlowTrainer
    
    id_Module_DecisionMaker --> id_Module_DataExporter