flowchart LR
    classDef NotStarted fill:#ff6666, stroke:#333
    classDef InProgress fill:#ffcc66, stroke:#333
    classDef Completed  fill:#339966, stroke:#333  
    
    Advisor(Advisor):::NotStarted



    Exporter(Exporter):::NotStarted



    Formatter(Formatter):::NotStarted



    Generator(Generator):::NotStarted



    Importer(Importer):::NotStarted
    Importer_CSV(CSV):::NotStarted
    Importer_JSON(JSON):::NotStarted



    Manipulator(Manipulator):::NotStarted
    Manipulator_Image(Image)


    Optimizer(Optimizer):::NotStarted



    Validator(Validator):::NotStarted



    Visualizer(Visualizer):::NotStarted