flowchart LR



    Growatt["Growatt"]
    EG4["24V Battery Bank"]
    EngineBattery["12V Engine Battery"]

    USBRelay00["USB Relay 00"]
    USBRelay01["USB Relay 01"]
    USBRelay02["USB Relay 02"]
    5V10ARelay00["5V 10A Relay 00"]
    5V10ARelay01["5V 10A Relay 01"]
    5V10ARelay02["5V 10A Relay 02"]
    5V10ARelay03["5V 10A Relay 03"]
    5V10ARelay04["5V 10A Relay 04"]
    5V10ARelay05["5V 10A Relay 05"]
    5V10ARelay06["5V 10A Relay 06"]
    5V10ARelay07["5V 10A Relay 07"]
    5V10ARelay08["5V 10A Relay 08"]
    5V10ARelay09["5V 10A Relay 09"]
    120VRelay00["120VAC Relay 00"]
    120VRelay01["120VAC Relay 01"]
    120VRelay02["120VAC Relay 02"]
    120VRelay03["120VAC Relay 03"]
    120VRelay04["120VAC Relay 04"]
    120VRelay05["120VAC Relay 05"]
    120VRelay06["120VAC Relay 06"]
    120VRelay07["120VAC Relay 07"]

    24V-5V_Converter["24V to 5V Converter"]
    Pi["Raspberry Pi <br> 192.168.12.156"]
    TMobile["T-Mobile Hotspot"]
    TPLinkWiFi["TPLink WiFi Router"]
    ATT["ATT Hotspot"]

    24V-12V_Converter["24V to 12V Converter"]
    NaturesHead["Composting Toilet Fan"]
    Stove["Stove"]
    MaxxairFan1["Maxxair Fan Front"]
    MaxxairFan2["Maxxair Fan Rear"]
    AlfaBooster["Alfa Camp Pro 2"]
    Furnace["Furnace"]

    24V-24V_Stabilizer["24V Stabilizer"]
    Freezer1["Freezer 1 Top"]
    Freezer2["Freezer 2 Front"]
    Freezer3["Freezer 2 Rear"]
    CabinLights["Cabin Lights"]
    DriverLight["Driver Light"]
    PassengerLight["Passenger Light"]
    BedLight["Bed Light"]
    KitchenLight["Kitchen Light"]

    24V-120VAC_Inverter["24V to 120VAC Converter"]
    Starlink["Starlink"]
    TPLinkWired["TPLink Wired Router"]
    Kettle["Electric Kettle"]
    AC["Mini Split AC/Heat Pump"]

    5V_FuseBox["5V Fuse Box"]
    12V_FuseBox["12V Fuse Box"]
    24V_FuseBox["24V Fuse Box"]
    120V_BreakerBox["120VAC Circuit Breaker Box"]
    
    EG4 --> 24V-5V_Converter
    subgraph 5V
        24V-5V_Converter --> 5V_FuseBox
        5V_FuseBox --> Pi
        5V_FuseBox --> USBRelay00
        USBRelay00 --> TMobile
        5V_FuseBox --> USBRelay01
        USBRelay01 --> TPLinkWiFi
        5V_FuseBox --> USBRelay02 
        USBRelay02 --> ATT
    end

    EG4 --> 24V-12V_Converter
    subgraph 12V
        24V-12V_Converter --> 12V_FuseBox
        12V_FuseBox --> 5V10ARelay00
        5V10ARelay00 --> NaturesHead
        12V_FuseBox --> 5V10ARelay01
        5V10ARelay01 --> Stove
        12V_FuseBox --> 5V10ARelay02
        5V10ARelay02 --> Furnace
        12V_FuseBox --> 5V10ARelay03
        5V10ARelay03 --> MaxxairFan1
        12V_FuseBox --> 5V10ARelay04
        5V10ARelay04 --> MaxxairFan2
        12V_FuseBox --> 5V10ARelay05
        5V10ARelay05 --> AlfaBooster
    end

    EG4 --> 24V-24V_Stabilizer
    subgraph 24V
        24V-24V_Stabilizer --> 24V_FuseBox
        24V_FuseBox --> 5V10ARelay06
        5V10ARelay06 --> Freezer1
        5V10ARelay06 --> Freezer2
        5V10ARelay06 --> Freezer3

        24V_FuseBox --> 5V10ARelay07
        5V10ARelay07 --> CabinLights

        24V_FuseBox --> 5V10ARelay08
        5V10ARelay08 --> BedLight

        24V_FuseBox --> 5V10ARelay09
        5V10ARelay09 --> KitchenLight

        24V_FuseBox --> 5V10ARelay10
        5V10ARelay10 --> DriverLight

        24V_FuseBox --> 5V10ARelay11
        5V10ARelay11 --> PassengerLight
    end

    EG4 --> 24V-120VAC_Inverter
    EG4 --> Growatt
    subgraph 120V
        24V-120VAC_Inverter --> 120V_BreakerBox
        Growatt --> 120V_BreakerBox
        120V_BreakerBox --> 120VRelay00
        120VRelay00 --> Starlink
        120V_BreakerBox --> 120VRelay01
        120VRelay01 --> TPLinkWired
        120V_BreakerBox --> 120VRelay02
        120VRelay02 --> Kettle
        120V_BreakerBox --> 120VRelay03
        120VRelay03 --> AC
    end
    





    